variables:
  GHC: "8.10.4"
  PKG: interval-algebra

image: registry.novisci.com/nsstat/statocker/haskell:8.10.4

before_script:
  - export VERSION=$(grep -e '^version:' interval-algebra.cabal | sed 's/version:[[:space:]]*//g')

stages:
  - docker
  - test
  - coverage

docker-build:
 stage : docker
 image: docker:19.03.8
 script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin  $CI_REGISTRY
    - docker build --tag $CI_REGISTRY_IMAGE/$PKG-build:$VERSION --tag $CI_REGISTRY_IMAGE/$PKG-build:latest .
    - docker push $CI_REGISTRY_IMAGE/$PKG-build:$VERSION
    - docker push $CI_REGISTRY_IMAGE/$PKG-build:latest

test:
  stage: test
  image: registry.novisci.com/nsstat/$PKG/$PKG-build:latest
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - dist-newstyle/
  script:
    - ghc --version
    - cabal --version
    - cabal test --test-show-details=always --enable-coverage

coverage-report:
  stage: coverage
  image: registry.novisci.com/nsstat/$PKG/$PKG-build:latest
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - dist-newstyle/
  script:
    - echo $VERSION
    - ls dist-newstyle
    - DISTPATH=dist-newstyle/build/x86_64-linux/ghc-$GHC/$PKG-$VERSION/hpc/vanilla
    - hpc report $DISTPATH/tix/$PKG-$VERSION/interval-algebra-$VERSION.tix --hpcdir=$DISTPATH/mix/$PKG-$VERSION
    - mkdir coverage
    - hpc report --xml-output --per-module $DISTPATH/tix/$PKG-$VERSION/interval-algebra-$VERSION.tix --hpcdir=$DISTPATH/mix/$PKG-$VERSION > coverage/coverage.xml
  artifacts:
    reports:
      cobertura: coverage/coverage.xml