image: haskell:8.8.3

variables:
  PKG: interval-algebra

cache:
  paths:
    - dist-newstyle

test:
  stage: test
  script:
    - ghc --version
    - cabal --version
    - cabal update
    - cabal install witherable --lib
    - cabal test --test-show-details=always 
