variables:
  GHC: "9.2.2"
  PKG: interval-algebra

# Tag all jobs with nsstat so that the nsstat runner is used:
# https://gitlab.com/groups/TargetRWE/epistats/-/runners/16673355
default: 
  tags: ["nsstat"]

# run on merge request and default branch
workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'

stages:
  - prep
  - build
  - test
  - coverage

build-vars:
  stage: prep
  script:
    - echo VERSION=$(grep -e '^version:' interval-algebra.cabal | sed 's/version:[[:space:]]*//g') >> .env
  artifacts:
    reports:
      dotenv: .env

is-draft: 
  stage: prep
  rules: 
    - if: '$CI_COMMIT_MESSAGE =~ /-draft/'
  script:
    - echo DRAFT=true >> draft.env
  artifacts:
    reports:
      dotenv: draft.env 

checks:
  stage: prep
  image: registry.gitlab.com/targetrwe/epistats/nsstat/nsbuild/haskell:${GHC}
  script:
    - hlint --version
    - ./ci/ci-lint.sh
    - ./ci/ci-check-format.sh

docker-build:
 stage : build
 image: docker:20.10.16
 needs:
    - job: checks
    - job: build-vars
      artifacts: true
 script:
    - ./ci/ci-build-docker.sh 

test:
  stage: test
  needs:
    - job: build-vars
      artifacts: true
    - job: is-draft
      artifacts: true
      optional: true
    - job: docker-build
      optional: true
  image: registry.gitlab.com/targetrwe/epistats/nsstat/$PKG/$PKG-build:${VERSION}
  artifacts:
    paths:
    - "**/*.tix"
    - "**/*.mix"
  script:
    - ./ci/ci-cabal-test.sh

coverage-report:
  stage: coverage
  image: registry.gitlab.com/targetrwe/epistats/nsstat/$PKG/$PKG-build:latest
  needs:
    - job: build-vars
      artifacts: true
    - job: test
      artifacts: true
  script:
    - ./ci/ci-coverage.sh
