image: haskell:8.8.3

variables:
  PKG: interval-algebra

cache:
  paths:
    - .stack
    - .stack-work
    - target

test:
  stage: test
  script:
    - ghc --version
    - cabal test --test-show-details=always 
