image: registry.novisci.com/nsstat/statocker/haskell:8.10.4

variables:
  PKG: interval-algebra

cache:
  paths:
    - dist-newstyle

test:
  stage: test
  script:
    - ghc --version
    - cabal --version
    # - cabal install --lib
    - cabal test --test-show-details=always 
