variables:
  GHC: "8.10.7"
  PKG: interval-algebra

# run on merge request and default branch
workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'

stages:
  - prep
  - build
  - test
  - coverage

build-vars:
  stage: prep
  script:
    - echo VERSION=$(grep -e '^version:' interval-algebra.cabal | sed 's/version:[[:space:]]*//g') >> .env
  artifacts:
    reports:
      dotenv: .env

is-draft: 
  stage: prep
  rules: 
    - if: '$CI_COMMIT_MESSAGE =~ /-draft/'
  script:
    - echo DRAFT=true >> draft.env
  artifacts:
    reports:
      dotenv: draft.env 

docker-build:
 stage : build
 image: docker:19.03.8
 needs:
    - job: build-vars
      artifacts: true
 script:
    - ./ci/ci-build-docker.sh 

test:
  stage: test
  needs:
    - job: build-vars
      artifacts: true
    - job: is-draft
      artifacts: true
      optional: true
    - job: docker-build
      optional: true
  image: registry.novisci.com/nsstat/$PKG/$PKG-build:${VERSION}
  artifacts:
    paths:
    - dist-newstyle/build/x86_64-linux/ghc-$GHC/$PKG-$VERSION/hpc/vanilla
  script:
    - ./ci/ci-cabal-test.sh

coverage-report:
  stage: coverage
  image: registry.novisci.com/nsstat/$PKG/$PKG-build:latest
  needs:
    - job: build-vars
      artifacts: true
    - job: test
      artifacts: true
  script:
    - ./ci/ci-coverage.sh
